---
title: "Meu primeiro Dash"
author: "Professora maravilhosa"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    self-contained: true
---

```{r setup, include=FALSE}
rm(list=ls())  #limpa  o ambient
if (!require(pacman)) install.packages("pacman") #garante que tem o pacman
pacman::p_load(tidyverse, rio, sf, rnaturalearth,  geobr,
               lubridate, ggspatial, ggthemes, gsubfn, ggsn,
               leaflet, htmlwidgets, flexdashboard, shiny, plotly ) 
```

Column {data-width=650}
-----------------------------------------------------------------------

### Mapa

Mude o mapa abaixo para outra latitude longitude se seu interesse (por exemplo, escolha um local e procure no Google suas coordenadas). Mude também o texto para que seja referente ao local que escolheu. 
```{r}
leaflet() %>%
  addTiles() %>%  # Add default OpenStreetMap map tiles
  addMarkers(lng=174.768, lat=-36.852, popup="The birthplace of R")

```

Column {data-width=350}
-----------------------------------------------------------------------

### Mapa 1

Acrescente aqui um mapa do mundo como feito na aula 31. Pode sr o mesmo gráfico que fez para o exercício daquela aula. Sugestão: use o pacote Natural Earth como o que usamos na aula 31. 

```{r}

```

### Mapa 2

Acrescente um gráfico do Brasil usando shapefiles ou o pacote geobr, como feito na aula 32. Pode ser o gráfico que fez naquela aula, caso tenha feito o exercício. 

```{r}

```

